name: Docker build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
    - .github/workflows/docker.yml
    - charts/argo-test/**
    - index.html
    - Dockerfile
  push:
    tags: [v*]
    branches: [main]
  workflow_dispatch:

jobs:
  docker:
    permissions:
      packages: write
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=sha,enable=${{ !startsWith(github.ref, 'refs/tags/') }}
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
        flavor: |
          latest=auto

    - name: Build image
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        push: true
