name: Docker build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
    - .github/workflows/docker.yml
    - charts/argo-test/**
    - index.html
    - Dockerfile
  push:
    branches: [main]
    tags: [v*]
  workflow_dispatch:
    inputs:
      push:
        required: false
        type: boolean
        default: false

jobs:
  docker:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to ghcr.io
      if: startsWith(github.ref, 'refs/tags/') || inputs.push
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ github.repository }}
        tags: |
          type=sha,enable=${{ !startsWith(github.ref, 'refs/tags/') }}
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
        flavor: |
          latest=auto

    - name: Build image
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        push: ${{ startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && inputs.push) }}
